let authMode='login';
    const state={role:'user',view:'bfi',survey:false,bfiIntro:false,answers:{},qpage:1,game:null,stagResults:{},profileUser:null,experiments:['猎鹿博弈 · 双人小组任务','猎鹿博弈 · 出行安排','囚徒困境 · 标准局']};
    const stagScenes={
      task:{no:'01',title:'双人小组任务',short:'你和另一名同学连续进行 10 轮项目决策，每轮同时选择任务投入方式。',a:'认真准备共同展示',b:'只完成最低限度任务',aText:'只有双方都认真准备，小组展示效果才会很好，双方获得最高收益。',bText:'收益不如共同认真准备高，但风险较小，能获得稳定收益。'},
      travel:{no:'02',title:'出行安排',short:'你和另一名同学准备去同一地点参加活动，连续进行 10 轮出行安排。',a:'一起拼车',b:'各自坐公交',aText:'只有双方都选择拼车才能成功，节省时间并获得最高收益。',bText:'虽然不如成功拼车高效，但风险较小，能够稳定到达目的地。'}
    };
    const bfi=['是健谈的','容易挑剔他人','做事彻底、可靠','容易情绪低落','富有创造性','比较含蓄、安静','乐于助人且无私','有时会粗心大意','能很好地应对压力','对许多事物好奇','精力充沛','有时会与他人争执','值得信赖地完成工作','容易紧张','善于深入思考','能激发他人热情','天性宽容','做事容易缺乏条理','经常忧虑','想象力活跃','比较安静','通常信任他人','有时会有点懒惰','情绪稳定','有创造力','性格坚定、自信','有时冷淡','能坚持到任务完成','情绪多变','重视艺术与审美','有时害羞拘谨','体贴、友善','做事有效率','在紧张情境中冷静','偏好常规','外向善于社交','有时态度粗鲁','会制定计划并执行','容易紧张不安','喜欢探索复杂观点','对艺术兴趣不大','喜欢与他人合作','容易分心','对艺术很有鉴赏力'];
    const users=[['林知夏','U-1024','186','38','高开放 · 高宜人','已完成'],['周子墨','U-1023','172','34','高尽责 · 稳定','已完成'],['陈屿','U-1022','168','29','高外向 · 高开放','已完成'],['许一诺','U-1021','151','24','待生成','未完成'],['江岚','U-1020','146','31','高宜人 · 稳定','已完成']];
    const profileOrder=['E','A','C','N','O'];
    const personalityProfiles=[{E:3.2,A:4.3,C:3.8,N:2.1,O:4.6},{E:2.8,A:3.7,C:4.6,N:1.9,O:3.4},{E:4.5,A:3.2,C:3.6,N:2.7,O:4.4},null,{E:3.0,A:4.5,C:3.9,N:1.8,O:3.5}];
    const personalityMeta={
      E:{name:'外向性',english:'Extraversion',general:'较低分表示更内向，较高分表示更外向。',bands:['你非常内向，强烈偏好独处和安静环境，而不是社交互动。','你有些内向，通常更喜欢独处，但也能接受有限的社交互动。','你的社交倾向较为平衡，既能适应社交场合，也能适应独处。','你有些外向，通常会寻求社交互动，并且在群体中较有活力。','你非常外向，强烈寻求社交互动，非常有活力且外向。']},
      A:{name:'宜人性',english:'Agreeableness',general:'较低分表示更具对抗性、较不信任他人，较高分表示更友善、更愿意合作。',bands:['你非常竞争和怀疑，强烈优先考虑自身利益，并且倾向于对抗。','你倾向于竞争和怀疑，通常更优先考虑自身利益。','你能较好地平衡合作与自我主张。','你通常合作且信任他人，重视和谐与他人的福祉。','你非常合作且信任他人，强烈重视和谐与他人的福祉。']},
      C:{name:'尽责性',english:'Conscientiousness',general:'较低分表示较不严谨、较随性，较高分表示更有条理、更自律。',bands:['你非常自发且灵活，强烈偏好适应变化，而不是严格计划。','你有些自发且灵活，通常更偏好适应变化，而不是严格计划。','你在结构性和灵活性之间保持平衡。','你通常有条理且自律，偏好结构化、系统化的方法。','你非常有条理且自律，强烈偏好结构化、系统化的方法。']},
      N:{name:'神经质',english:'Neuroticism',general:'较低分表示情绪更稳定，较高分表示更容易焦虑、紧张或情绪敏感。',bands:['你情绪非常稳定且有韧性，在压力下也能非常冷静。','你情绪较稳定且有韧性，通常能在压力下保持冷静。','你具有中等程度的情绪稳定性，会有正常的压力反应。','你有些情绪敏感，更频繁地体验担忧和压力。','你非常情绪敏感，非常频繁地体验担忧和压力。']},
      O:{name:'开放性',english:'Openness to Experience',general:'较低分表示更偏好熟悉和传统的方式，较高分表示更开放、更有创造性和好奇心。',bands:['你强烈偏好熟悉的方法和传统思维。','你有些偏好熟悉的方法和传统思维。','你能在创新和传统之间保持平衡。','你通常乐于接受新体验，有创造力，并且具有智识好奇心。','你非常乐于接受新体验，非常有创造力，并且具有强烈的智识好奇心。']}
    };
    const userNav=[['bfi','◇','BFI-44 问卷'],['games','◎','博弈 PK'],['rank','↗','排行榜']];
    const adminNav=[['users','◉','用户数据'],['experiments','⌁','博弈实验'],['accounts','⊕','注册与登录'],['pages','▤','页面管理'],['content','✦','内容管理']];
    const titles={bfi:['BFI-44 人格问卷','完成问卷后即可解锁全部博弈实验'],games:['博弈 PK','选择实验，观察你的合作与决策模式'],rank:['排行榜','看看本周谁最擅长建立合作'],users:['用户数据','掌握参与情况、得分与人格结果'],experiments:['博弈实验','配置、排序并维护实验项目'],accounts:['注册与登录管理','管理访问策略、账号事件与登录安全'],pages:['页面管理','维护页面结构、状态与访问范围'],content:['内容管理','编辑问卷说明、实验场景和平台内容']};
    function setAuth(mode,btn){authMode=mode;document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.getElementById('nickname').classList.toggle('hidden',mode==='login');document.getElementById('auth-title').textContent=mode==='login'?'登录你的账号':'创建研究账号';document.getElementById('submit-auth').textContent=mode==='login'?'登录并进入 →':'注册并进入 →'}
    function submitAccount(){const email=document.getElementById('login-email').value.trim().toLowerCase();if(!email){toast('请输入邮箱');return}enter(authMode==='login'&&email.startsWith('admin@')?'admin':'user')}
    function enter(role){state.role=role;state.view=role==='user'?'bfi':'users';document.getElementById('auth').classList.add('hidden');document.getElementById('app').classList.remove('hidden');setupNav();render()}
    function logout(){document.getElementById('app').classList.add('hidden');document.getElementById('auth').classList.remove('hidden')}
    function setupNav(){const admin=state.role==='admin',items=admin?adminNav:userNav;document.getElementById('space-title').textContent=admin?'管理控制台':'参与者空间';document.getElementById('crumb-role').textContent=admin?'管理控制台':'参与者空间';document.getElementById('profile-name').textContent=admin?'实验管理员':'林知夏';document.getElementById('profile-id').textContent=admin?'admin@yangmind.cn':'ID · U-1024';document.getElementById('avatar').textContent=admin?'管':'林';document.getElementById('nav').innerHTML='<small>'+(admin?'实验管理':'实验参与')+'</small>'+items.map(i=>`<button data-view="${i[0]}" onclick="go('${i[0]}')"><span>${i[1]}</span>${i[2]}</button>`).join('')+`<button onclick="switchRole()"><span>⇄</span>切换至${admin?'用户端':'管理端'}</button>`}
    function switchRole(){state.role=state.role==='user'?'admin':'user';state.view=state.role==='user'?'bfi':'users';setupNav();render()}
    function go(v){state.view=v;render()}
    function render(){document.querySelectorAll('.nav [data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));document.getElementById('page-title').textContent=titles[state.view][0];document.getElementById('page-sub').textContent=titles[state.view][1];const c=document.getElementById('content');c.innerHTML=({bfi:renderBFI,games:renderGames,rank:renderRank,users:renderUsers,experiments:renderExperiments,accounts:renderAccounts,pages:()=>placeholder('▤','页面管理','路由、可见范围与发布状态已为单文件演示版预留。'),content:()=>placeholder('✦','内容管理','可在此维护问卷说明、博弈场景、规则与公告。')})[state.view]();}
    function renderBFI(){if(state.survey)return `<div class="page"><section class="hero card"><div><div class="eyebrow">已完成 · 质量检查通过</div><h2>你的人格轮廓已生成</h2><p>结果用于解释博弈中的决策倾向，不代表能力高低。</p></div><div class="ring" style="--p:360deg"><b>100%</b></div></section><div class="statgrid" style="margin-top:18px">${['开放性 82','尽责性 74','外向性 66','宜人性 79','情绪敏感 48'].map(x=>`<div class="stat card"><span>人格维度</span><b>${x}</b><em>已生成</em></div>`).join('')}</div></div>`;let answered=Object.keys(state.answers).length,p=Math.round(answered/44*100),start=(state.qpage-1)*11,items=bfi.slice(start,start+11);return `<div class="page"><section class="hero card"><div><div class="eyebrow">参与博弈前置步骤</div><h2>先认识自己的决策底色</h2><p>BFI-44 用 44 个简短陈述了解你的五项人格维度。请根据真实、稳定的自己作答。</p></div><div class="ring" style="--p:${p*3.6}deg"><b>${p}%</b></div></section><div class="quality"><i>✓</i><div><b>质量保护已开启</b><small>系统检查作答时长、长串同选项与正反向项目一致性。</small></div></div><section class="question-card card"><div class="qhead"><div><span>第 ${state.qpage} / 4 组</span><br><b>请判断以下描述与你的符合程度</b></div><span>${answered} / 44 已作答</span></div>${items.map((q,i)=>{let id=start+i+1;return `<div class="qrow"><div class="qtext"><b>${String(id).padStart(2,'0')}</b>我认为自己是一个${q}的人。</div><div class="scale">${[1,2,3,4,5].map(v=>`<label><input type="radio" name="q${id}" ${state.answers[id]===v?'checked':''} onchange="answer(${id},${v})"><i></i>${v}</label>`).join('')}</div></div>`}).join('')}<div class="qfoot"><button class="secondary" onclick="qpage(-1)" ${state.qpage===1?'disabled':''}>← 上一组</button><span>答案仅保存在当前页面内存中</span><button class="primary" onclick="${state.qpage===4?'submitSurvey()':'qpage(1)'}">${state.qpage===4?'提交问卷':'下一组'} →</button></div></section>${pagination(state.qpage,4,'setQPage')}</div>`}
    const renderBFIQuestionnaire=renderBFI;
    renderBFI=function(){
      if(!state.survey&&!state.bfiIntro)return renderBfiIntro();
      return renderBFIQuestionnaire();
    }
    function renderBfiIntro(){return `<div class="page theory-page">
      <section class="theory-hero card">
        <div>
          <div class="eyebrow">BFI-44 · 理论导读</div>
          <h2>认识大五人格模型</h2>
          <p>在开始作答前，请先阅读以下简要介绍，了解问卷所测量的五项人格维度。</p>
        </div>
        <div class="theory-index"><small>理论基础</small><b>1.2</b></div>
      </section>
      <section class="theory-foundation card">
        <div class="eyebrow">1.2 理论基础</div>
        <h3>人格特质的五维框架</h3>
        <p>大五人格模型的五个维度源于对自然语言中人格描述词汇的统计分析，具体包括：</p>
      </section>
      <div class="dimension-grid">
        <article class="dimension-card card"><span class="dimension-letter">E</span><div><h3>外向性 <small>Extraversion · E</small></h3><p>描述个体与他人互动的倾向和能量来源。<strong>高分者</strong>通常表现为热情、健谈、喜欢社交、精力充沛；<strong>低分者</strong>则更倾向于独处、内敛、安静。</p></div></article>
        <article class="dimension-card card"><span class="dimension-letter">A</span><div><h3>宜人性 <small>Agreeableness · A</small></h3><p>反映个体与他人相处时的态度和行为倾向。<strong>高分者</strong>表现为友善、合作、乐于助人、富有同情心；<strong>低分者</strong>则可能较为冷漠、多疑、好竞争。</p></div></article>
        <article class="dimension-card card"><span class="dimension-letter">C</span><div><h3>尽责性 <small>Conscientiousness · C</small></h3><p>描述个体的自律性、责任感和目标导向程度。<strong>高分者</strong>通常做事有条理、可靠、勤奋、有毅力；<strong>低分者</strong>则可能较为随意、拖延、缺乏计划性。</p></div></article>
        <article class="dimension-card card"><span class="dimension-letter">N</span><div><h3>神经质 <small>Neuroticism · N</small></h3><p>反映个体情绪稳定性的程度。<strong>高分者</strong>往往更容易体验到焦虑、抑郁、愤怒等负面情绪，情绪波动较大；<strong>低分者</strong>情绪较为稳定，心态平和。</p></div></article>
        <article class="dimension-card card"><span class="dimension-letter">O</span><div><h3>开放性 <small>Openness to Experience · O</small></h3><p>体现个体对新事物、新观念的接受程度和创造力。<strong>高分者</strong>具有丰富的想象力、好奇心强、喜欢尝试新体验；<strong>低分者</strong>则更偏好常规、传统，对新事物持谨慎态度。</p></div></article>
      </div>
      <div class="theory-note"><b>阅读<br>提示</b><span>人格特质没有绝对的好坏之分。本问卷结果仅用于本次研究中的行为分析，不作为临床诊断依据。</span></div>
      <div class="theory-action card"><div><small>预计用时</small><b>6–8 分钟 · 共 44 题</b></div><button class="primary" onclick="beginBfiSurvey()">我已了解，开始填写 BFI-44 →</button></div>
    </div>`}
    function beginBfiSurvey(){state.bfiIntro=true;render()}
    function answer(id,v){state.answers[id]=v;render()}
    function qpage(d){state.qpage=Math.max(1,Math.min(4,state.qpage+d));render()}function setQPage(p){state.qpage=p;render()}
    function submitSurvey(){if(Object.keys(state.answers).length<44){toast('还有 '+(44-Object.keys(state.answers).length)+' 题未完成，请检查后提交');return}state.survey=true;toast('问卷已提交，博弈入口已解锁');render()}
    function renderGames(){if(state.game)return renderStagFlow();return `<div class="page">${state.survey?'':`<div class="alert"><i>!</i><div><b>博弈入口暂未解锁</b><small>完成 BFI-44 问卷后即可进入全部实验。</small></div></div>`}<div class="section-head"><div><div class="eyebrow">EXPERIMENT LOBBY</div><h2>选择一种博弈</h2><p>观察在不同收益结构下，你如何建立信任、权衡风险。</p></div></div><div class="games"><article class="game card ${state.survey?'':'locked'}"><div class="art prison"><span>01 · PRISONER</span><div class="bars">${'<i></i>'.repeat(5)}</div></div><div class="gamebody"><span>非零和 · 同时行动</span><h3>囚徒困境</h3><p>合作带来稳定收益，单方面背叛可能获得更高回报。</p><div class="stats"><span><b>10</b>轮/场</span><span><b>214</b>人参与</span><span><b>63%</b>合作率</span></div><button class="primary" onclick="startGame('囚徒困境')">${state.survey?'开始博弈':'完成问卷后解锁'} →</button></div></article><article class="game card ${state.survey?'':'locked'}"><div class="art stag"><span>02 · STAG HUNT</span><div class="forest"></div></div><div class="gamebody"><span>协调博弈 · 收益依赖</span><h3>猎鹿博弈</h3><p>现已包含“双人小组任务”和“出行安排”两个完整场景。</p><div class="stats"><span><b>20</b>轮共计</span><span><b>2</b>个场景</span><span><b>10/6/0</b>计分</span></div><button class="primary" onclick="startGame('猎鹿博弈')">${state.survey?'选择场景':'完成问卷后解锁'} →</button></div></article></div>${pagination(1,2)}</div>`}
    function startGame(name){if(!state.survey){toast('请先完成 BFI-44 问卷');return}if(name==='猎鹿博弈'){state.game={stage:'scenes'};render();return}toast('囚徒困境将在后续版本补充完整对局')}
    function renderStagFlow(){const g=state.game;if(g.stage==='scenes')return renderSceneSelect();const s=stagScenes[g.scene];if(g.stage==='intro')return renderSceneIntro(s);if(g.stage==='finish')return renderGameFinish(s);return renderRound(s)}
    function renderSceneSelect(){const doneCount=Object.keys(state.stagResults).length,allDone=doneCount===Object.keys(stagScenes).length;return `<div class="page"><button class="backbtn" onclick="exitGame()">← 返回博弈大厅</button><div class="section-head"><div><div class="eyebrow">STAG HUNT · TWO REQUIRED SCENARIOS</div><h2>完成两个猎鹿博弈场景</h2><p>两个场景均为必做项目，每个场景需要完整进行 10 轮。</p></div></div><div class="completion-banner card ${allDone?'complete':''}"><div><span>${allDone?'EXPERIMENT COMPLETE':'REQUIRED PROGRESS'}</span><b>${allDone?'两个场景均已完成':'必做进度：'+doneCount+' / 2'}</b><small>${allDone?'猎鹿博弈实验已计为完整完成。':'只有两个场景分别完成后才计为实验完成；重复同一场景不会增加进度。'}</small></div><strong>${doneCount}/2</strong></div><div class="scene-grid">${Object.entries(stagScenes).map(([id,s])=>{const done=!!state.stagResults[id],blocked=done&&!allDone;return `<article class="scenario-card card ${done?'completed':''}" data-no="${s.no}"><span class="scenario-status">${done?'✓ 已完成':'○ 必做场景'}</span><h3>${s.title}</h3><p>${s.short}</p><div class="scenario-meta"><i>10 轮</i><i>同时选择</i><i>${done?'得分 '+state.stagResults[id].score:'A / B'}</i></div><button class="primary" ${blocked?'disabled':''} onclick="openScene('${id}')">${blocked?'已完成，请继续另一场景':done?'重新体验该场景 →':'查看场景规则 →'}</button></article>`}).join('')}</div>${pagination(1,2)}</div>`}
    function openScene(id){state.game={stage:'intro',scene:id,round:1,myScore:0,opponentScore:0,history:[],last:null};render()}
    function renderSceneIntro(s){return `<div class="page"><button class="backbtn" onclick="backToScenes()">← 返回场景选择</button><section class="hero card"><div><div class="eyebrow">猎鹿博弈 · 场景 ${s.no}</div><h2>${s.title}</h2><p>${s.short}每轮你不能提前知道对方的选择，轮次结束后会看到双方上一轮的选择与得分。</p></div><div class="ring" style="--p:0deg"><b>0/10</b></div></section><div class="rule-layout" style="margin-top:18px"><section class="rule-copy card"><h3>你的两个选择</h3><p>你和对方在每一轮中同时做出决策。你的目标是在整个实验中尽可能获得更高的总分。</p><div class="options"><div class="option"><b>A：${s.a}</b><span>${s.aText}</span></div><div class="option"><b>B：${s.b}</b><span>${s.bText}</span></div></div></section><section class="matrix-card card"><h3>每轮得分规则</h3><div class="matrix"><div class="matrix-row head"><span>你 / 对方</span><span>A</span><span>B</span></div><div class="matrix-row"><span>A</span><span>10 / 10</span><span>0 / 6</span></div><div class="matrix-row"><span>B</span><span>6 / 0</span><span>6 / 6</span></div></div><p class="matrix-note">斜线前为你的得分，斜线后为对方的得分。双方都选 A 时收益最高，选 B 可获得稳定的 6 分。</p></section></div><div class="rule-actions"><small>请确认你已了解场景和计分规则。</small><button class="primary" onclick="beginRounds()">我已了解，开始第 1 轮 →</button></div></div>`}
    function beginRounds(){state.game.stage='play';render()}
    function renderRound(s){const g=state.game,history=g.history.slice().reverse();return `<div class="page"><button class="backbtn" onclick="backToScenes()">← 退出当前对局</button><section class="round-card card"><div class="roundtop"><div><div class="eyebrow">${s.title}</div><h2>现在是第 ${g.round} 轮</h2><p>请同时做出决策：你选择 A 还是 B？</p></div><div class="roundbadge">第 <b>${g.round}</b> / 10 轮</div></div><div class="roundbar">${Array.from({length:10},(_,i)=>`<i class="${i<g.history.length?'done':i===g.history.length?'now':''}"></i>`).join('')}</div><div class="scoreboard"><div class="scorebox"><span>你的累计得分</span><b>${g.myScore}</b></div><div class="versus">VS</div><div class="scorebox"><span>对方累计得分</span><b>${g.opponentScore}</b></div></div>${g.last?`<div class="last-result">上一轮：你选择 <b>${g.last.mine}</b>（${g.last.mine==='A'?s.a:s.b}），对方选择 <b>${g.last.theirs}</b>。你得 <b>${g.last.myPoints}</b> 分，对方得 <b>${g.last.theirPoints}</b> 分。</div>`:''}<div class="choice-title">请选择本轮行动</div><div class="choice-buttons"><button class="choice-btn" onclick="playRound('A')"><b>A · ${s.a}</b><span>${s.aText}</span><em>双方选 A：10 分</em></button><button class="choice-btn" onclick="playRound('B')"><b>B · ${s.b}</b><span>${s.bText}</span><em>稳定收益：6 分</em></button></div></section>${history.length?`<section class="history-card card"><div class="history-title">之前轮次的记录</div><div class="history-row head"><span>轮次</span><span>你的选择</span><span>对方选择</span><span>你的得分</span><span>对方得分</span></div>${history.map(h=>`<div class="history-row"><span>${h.round}</span><span><i class="choice-tag ${h.mine==='B'?'b':''}">${h.mine}</i></span><span><i class="choice-tag ${h.theirs==='B'?'b':''}">${h.theirs}</i></span><b>+${h.myPoints}</b><b>+${h.theirPoints}</b></div>`).join('')}</section>`:''}</div>`}
    function playRound(mine){const g=state.game,theirs=Math.random()<.64?'A':'B';let myPoints,theirPoints;if(mine==='A'&&theirs==='A'){myPoints=10;theirPoints=10}else if(mine==='A'){myPoints=0;theirPoints=6}else if(theirs==='A'){myPoints=6;theirPoints=0}else{myPoints=6;theirPoints=6}const result={round:g.round,mine,theirs,myPoints,theirPoints};g.history.push(result);g.myScore+=myPoints;g.opponentScore+=theirPoints;g.last=result;if(g.round>=10){state.stagResults[g.scene]={score:g.myScore,opponentScore:g.opponentScore,completed:true};g.stage='finish'}else{g.round++}render()}
    function renderGameFinish(s){const g=state.game,doneCount=Object.keys(state.stagResults).length,allDone=doneCount===Object.keys(stagScenes).length;return `<div class="page"><section class="finish card"><div class="trophy">${allDone?'✓':'✦'}</div><div class="eyebrow" style="justify-content:center;margin-top:20px">${allDone?'猎鹿博弈已全部完成':'场景已完成 · 总进度 '+doneCount+'/2'}</div><h2>${allDone?'两个必做场景均已完成':s.title+' · 10 轮结束'}</h2><p>${allDone?'本次猎鹿博弈实验现已计为完整完成。':'你已完成当前场景，还需要完成另一个场景，实验才会计为完整完成。'}</p><div class="finish-score">${g.myScore} 分</div><p>本场对方得分：${g.opponentScore} · 你选择 A：${g.history.filter(h=>h.mine==='A').length} 次 · 选择 B：${g.history.filter(h=>h.mine==='B').length} 次</p><div class="finish-actions"><button class="secondary" onclick="backToScenes()">查看场景进度</button><button class="primary" onclick="${allDone?'restartScene()':'openNextRequired()'}">${allDone?'重新体验当前场景':'继续下一个必做场景 →'}</button></div></section></div>`}
    function openNextRequired(){const id=Object.keys(stagScenes).find(id=>!state.stagResults[id]);if(id)openScene(id);else backToScenes()}
    function restartScene(){const id=state.game.scene;openScene(id)}function backToScenes(){state.game={stage:'scenes'};render()}function exitGame(){state.game=null;render()}
    function renderRank(){return `<div class="page"><section class="hero card"><div><div class="eyebrow">WEEKLY LEADERBOARD</div><h2>合作不只是策略，也是成绩</h2><p>排行榜综合累计得分、有效轮次与合作稳定性。</p></div><div class="ring" style="--p:278deg"><b>#12</b></div></section><section class="table card" style="margin-top:18px"><div class="tablehead"><h3>总排行榜</h3><input class="search" placeholder="搜索参与者"></div><div class="row header"><span>参与者</span><span>排名</span><span>场次</span><span>人格摘要</span><span>总得分</span><span>趋势</span></div>${users.map((u,i)=>`<div class="row"><span class="user"><i>${u[0][0]}</i><b>${u[0]}</b></span><b>#${i+1}</b><span>${u[3]}</span><span>${u[4]}</span><b>${u[2]}</b><span style="color:#269c7d">↑ ${i+1}</span></div>`).join('')}</section>${pagination(1,4)}</div>`}
    function renderUsers(){return `<div class="page"><div class="statgrid admin-stats">${[['总注册用户','1,284','↑ 12.6%'],['问卷完成率','92.4%','↑ 3.2%'],['有效博弈轮次','24,860','↑ 8.7%'],['平均合作率','67.8%','— 0.4%']].map(x=>`<div class="stat card"><span>${x[0]}</span><b>${x[1]}</b><em>${x[2]}</em></div>`).join('')}</div><section class="table card user-table"><div class="tablehead"><h3>用户与人格结果</h3><input class="search" placeholder="搜索姓名或 ID"></div><div class="row header"><span>用户</span><span>总得分</span><span>完成场次</span><span>人格摘要</span><span>问卷</span><span>操作</span></div>${users.map((u,i)=>`<div class="row"><span class="user"><i>${u[0][0]}</i><b>${u[0]}<small style="display:block;color:#999">${u[1]}</small></b></span><b>${u[2]}</b><span>${u[3]}</span><span>${u[4]}</span><span class="badge ${u[5]==='已完成'?'':'warn'}">${u[5]}</span><button class="secondary profile-view-btn" ${personalityProfiles[i]?'onclick="openProfile('+i+')"':'disabled title="完成问卷后生成"'}>${personalityProfiles[i]?'查看画像':'待生成'}</button></div>`).join('')}</section>${pagination(1,8)}</div>${state.profileUser===null?'':renderProfileModal()}`}
    function openProfile(i){if(!personalityProfiles[i]){toast('该用户尚未完成问卷，暂时没有人格画像');return}state.profileUser=i;render()}
    function closeProfile(){state.profileUser=null;render()}
    function personalityBand(code,score){const index=score<=1.5?0:score<2.5?1:score<3.5?2:score<4.5?3:4;return personalityMeta[code].bands[index]}
    function renderProfileModal(){const i=state.profileUser,u=users[i],scores=personalityProfiles[i];return `<div class="profile-overlay" onclick="closeProfile()"><section class="profile-modal" role="dialog" aria-modal="true" aria-label="${u[0]}的人格画像" onclick="event.stopPropagation()"><header class="profile-modal-head"><div class="profile-person"><i>${u[0][0]}</i><div><b>${u[0]} · 人格详细档案</b><small>${u[1]} · BFI-44 已完成</small></div></div><button onclick="closeProfile()" aria-label="关闭">×</button></header><div class="profile-modal-body"><div class="profile-intro"><div><div class="eyebrow">PERSONALITY PROFILE · E / A / C / N / O</div><h2>大五人格维度与具体倾向</h2><p>人格分数采用 1 到 5 的量表，分数表示该用户在各项特质上的稳定倾向。</p></div><span class="scale-badge">量表范围 1.0–5.0</span></div><div class="dimension-explain">${profileOrder.map(code=>`<article><b>${code} · ${personalityMeta[code].name}</b><small>${personalityMeta[code].general}</small></article>`).join('')}</div><div class="personality-scores">${profileOrder.map(code=>{const m=personalityMeta[code],score=scores[code];return `<article class="score-card"><div class="score-title"><i>${code}</i><div><b>${m.name}</b><small>${m.english}</small></div><strong>${score.toFixed(1)} / 5.0</strong></div><div class="score-track"><i style="width:${score/5*100}%"></i></div><p>${personalityBand(code,score)}</p></article>`}).join('')}</div><section class="decision-guide"><h3>决策指南</h3><p>在做决定时，请考虑你的人格特征。</p><p>做出符合你人格特征、感觉自然且真实的选择。</p><p>请根据一个具有上述特征的人在这种情境下可能会如何自然行动来作答。</p><p><b>请记住：</b>你的人格画像代表了你稳定的特征和倾向。</p></section></div></section></div>`}
    function renderExperiments(){return `<div class="page"><section class="hero card"><div><div class="eyebrow">EXPERIMENT OPERATIONS</div><h2>管理博弈实验</h2><p>配置实验顺序、轮次与开放状态。</p></div><button class="primary" onclick="addExperiment()">＋ 添加实验</button></section><section class="card" style="margin-top:18px"><div class="tablehead"><h3>实验列表</h3><span style="font-size:9px;color:#999">使用箭头调整顺序</span></div><div class="manage-list">${state.experiments.map((x,i)=>`<div class="manage-item"><i>${String(i+1).padStart(2,'0')}</i><div><b>${x}</b><small>10 轮 · 进行中</small></div><span class="badge">进行中</span><div class="actions"><button onclick="moveExp(${i},-1)">↑</button><button onclick="moveExp(${i},1)">↓</button><button onclick="toast('已进入修改状态')">修改</button><button class="del" onclick="delExp(${i})">删除</button></div></div>`).join('')}</div></section>${pagination(1,3)}</div>`}
    function addExperiment(){state.experiments.push('新建博弈实验');render();toast('已添加实验草稿')}function delExp(i){state.experiments.splice(i,1);render();toast('已删除该实验')}function moveExp(i,d){let j=i+d;if(j<0||j>=state.experiments.length)return;[state.experiments[i],state.experiments[j]]=[state.experiments[j],state.experiments[i]];render()}
    function renderAccounts(){return `<div class="page"><div class="settings">${[['✉','注册策略','开放邮箱注册，新用户验证邮箱后激活。'],['⌁','登录安全','连续 5 次登录失败后锁定 15 分钟。'],['#','实验邀请码','用于定向招募实验参与者。']].map(x=>`<article class="setting card"><i>${x[0]}</i><h3>${x[1]}</h3><p>${x[2]}</p><button class="secondary" onclick="toast('设置已更新')">管理设置</button></article>`).join('')}</div><section class="table card" style="margin-top:18px"><div class="tablehead"><h3>账号事件</h3></div>${['林知夏 完成邮箱验证并首次登录','管理员 修改用户 U-1019 的状态','许一诺 使用邀请码注册','系统 阻止了一次异常登录尝试'].map((x,i)=>`<div class="row" style="grid-template-columns:1fr 100px 50px"><span>${x}</span><span>${i+2} 小时前</span><button class="secondary" style="height:28px;padding:0">查看</button></div>`).join('')}</section>${pagination(1,6)}</div>`}
    function placeholder(icon,title,text){return `<div class="page"><div class="placeholder card"><i>${icon}</i><h2>${title}</h2><p>${text}</p><button class="primary" onclick="toast('已新建一个草稿')">＋ 新建草稿</button></div>${pagination(1,4)}</div>`}
    function pagination(current,total,fn){return `<div class="pages">${Array.from({length:Math.min(total,4)},(_,i)=>`<button class="${current===i+1?'active':''}" onclick="${fn?fn+'('+(i+1)+')':''}">${i+1}</button>`).join('')}<button>›</button></div>`}
    function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2800)}
